version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
clone_depth: 2
environment:
  nuget_user: localmed
  nuget_password:
    secure: 2rbqdU+Xk3dgYQajqCrcWK1dOgTwnwBiJqNA2xMr7tQ=
install:
- cmd: nuget sources add -Name localmed -Source https://www.myget.org/F/localmed/api/v3/index.json -UserName %nuget_user% -Password %nuget_password%
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  server: https://www.myget.org/F/localmed/api/v2/package
  api_key:
    secure: AURbJMRwqYr6CThnpQMeo5XYaTrBLIYhq+Red3oklaihM3RGZ0QNs3qLMpdICQBw
  skip_symbols: true
  on:
    branch: master