version: 1.0.{build}
configuration: Release
clone_depth: 2
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: >-
    mkdir .artifacts

    cd Diversion

    nuget pack Diversion.csproj -p Configuration=Release -OutputDirectory ..\.artifacts

    cd ..\Diversion.CLI

    nuget pack Diversion.CLI.csproj -p Configuration=Release -Tool -OutputDirectory ..\.artifacts
artifacts:
- path: .artifacts\*.nupkg
deploy:
- provider: NuGet
  server: https://www.myget.org/F/localmed/api/v3/index.json
  api_key:
    secure: AURbJMRwqYr6CThnpQMeo5XYaTrBLIYhq+Red3oklaihM3RGZ0QNs3qLMpdICQBw
  skip_symbols: true
  on:
    branch: master