version: 1.0.{build}
configuration: Release
clone_depth: 2
before_build:
- nuget restore
build:
  verbosity: minimal
after_build:
- mkdir .artifacts
- cd Diversion
- nuget pack -p Configuration=Release -OutputDirectory ..\.artifacts
- cd ..\Diversion.CLI
- nuget pack -p Configuration=Release -Tool -OutputDirectory ..\.artifacts
- cd ..
artifacts:
- path: .artifacts\*.nupkg
deploy:
- provider: NuGet
  server: http://nuget.localmed.org/api/v2
  api_key:
    secure: OEqrzo1+tAdt+bxGRqDBozBE1hPgt1UvCpcB4w5YSt2cciPfw4/4sP4V1UgQmoKK
  skip_symbols: true
  on:
    branch: master