version: 1.0.{build}
configuration: Release
clone_depth: 2
environment:
  nuget_user: localmed
  nuget_password:
    secure: 2rbqdU+Xk3dgYQajqCrcWK1dOgTwnwBiJqNA2xMr7tQ=
install:
- cmd: nuget sources add -Name localmed -Source https://www.myget.org/F/localmed/api/v3/index.json -UserName %nuget_user% -Password %nuget_password%
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: >-
    mkdir .artifacts

    cd Diversion

    nuget pack -p Configuration=Release -OutputDirectory ..\.artifacts

    cd ..\Diversion.CLI

    nuget pack -p Configuration=Release -Tool -OutputDirectory ..\.artifacts
artifacts:
- path: .artifacts\*.nupkg
deploy:
- provider: NuGet
  server: https://www.myget.org/F/localmed/api/v3/index.json
  api_key:
    secure: AURbJMRwqYr6CThnpQMeo5XYaTrBLIYhq+Red3oklaihM3RGZ0QNs3qLMpdICQBw
  skip_symbols: true
  on:
    branch: master